apiVersion: v1
kind: ServiceAccount
metadata:
  name: calm-karbon
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: calm-karbon-secret
  namespace: default
  annotations:
    kubernetes.io/service-account.name: calm-karbon
type: kubernetes.io/service-account-token
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: calm-admin
subjects:
- kind: ServiceAccount
  name: calm-karbon
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""